### ISSUE TITLE
LSP: write after end error

### ISSUE THREAD

**Issue by Hezkore** [Hezkore/vscode-blitzmax-support#2]
```
Rejected promise not handled within 1 second: Error [ERR_STREAM_WRITE_AFTER_END]: write after end

*/usr/share/code/resources/app/out/bootstrap-fork.js*

stack trace: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:266:14)
    at Socket.write (_stream_writable.js:315:5)
    at /home/hezkore/Projects/Code/VSCode/vscode-blitzmax-support/node_modules/vscode-jsonrpc/lib/node/ril.js:90:29
    at new Promise (<anonymous>)
    at WritableStreamWrapper.write (/home/hezkore/Projects/Code/VSCode/vscode-blitzmax-support/node_modules/vscode-jsonrpc/lib/node/ril.js:80:16)
    at StreamMessageWriter.doWrite (/home/hezkore/Projects/Code/VSCode/vscode-blitzmax-support/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:100:33)
    at /home/hezkore/Projects/Code/VSCode/vscode-blitzmax-support/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:91:29
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processImmediate (internal/timers.js:429:9)
    at process.callbackTrampoline (internal/async_hooks.js:120:14)
```

**Comment by Hezkore** [comment]
fixed in 1b9ed4de1c17f2a58222c22086c696da6f21cd28
